services:
  hazardswatch:
    platform: linux/x86_64
    build:
      context: .
      args:
        - NODE_ENV=${NODE_ENV}
    env_file:
      - .env
    ports:
      - ${PORT}:3000

networks:
    default:
      name:  ${AHW_DOCKER_NETWORK}
      external: true