services:
  hazardswatch:
    platform: linux/x86_64
    build:
      context: .
      args:
        - NODE_ENV=${NODE_ENV}
        - ANALYTICS_PROPERTY_ID=${ANALYTICS_PROPERTY_ID}
        - BITLY_TOKEN=${BITLY_TOKEN}
        - DEBUG= ${DEBUG}
        - FACEBOOK_PIXEL_ID=${FACEBOOK_PIXEL_ID}
        - FEATURE_ENV=${FEATURE_ENV}
        - GOOGLE_CUSTOM_SEARCH_CX=${GOOGLE_CUSTOM_SEARCH_CX}
        - GOOGLE_SEARCH_API_KEY=${GOOGLE_SEARCH_API_KEY}
        - HW_API=${HW_API}
        - HW_CMS_API=${HW_CMS_API}
        - MAPBOX_TOKEN=${MAPBOX_TOKEN}
        - TWITTER_CONVERSION_ID=${TWITTER_CONVERSION_ID}
        - ASSET_PREFIX=${ASSET_PREFIX}
        - ECWMF_HRES_TIMESTAMPS_URL=${ECWMF_HRES_TIMESTAMPS_URL}
        - METADATA_BASE_URL=${METADATA_BASE_URL}
    volumes:
        - ./next/static/:/app/nginx/.next/static
    ports:
      - ${PORT}:3000
networks:
    default:
      name:  ${AHW_DOCKER_NETWORK}
      external: true